name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        
    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Run format
      run: make format

    - name: Run Tests
      run: make tests
